-- Create DataBase

Blinkit_new

-- Create Order_details Table

create table order_details
(OrderDetailID varchar(100) primary key,
OrderID varchar(100),
ProductID varchar(100),
Quantity numeric,
UnitPrice decimal(10,2),
LineTotal decimal(10,2)
);

-- Create Products Table

create table products
(ProductID varchar(100) primary key,
ProductName varchar(100),
Category varchar(100),
SubCategory varchar(100),
Price decimal(10,2),
CostPrice decimal(10,2)
);

--Create Table Stores

create table stores
(StoreID varchar(100) primary key,
StoreName varchar(100),
City varchar(100),
Area varchar(100),
OpenSince date,
PickupOption varchar(100)
);

-- Create Table Orders

create table orders
(OrderID varchar(100) primary key,
CustomerID varchar(100),
StoreID varchar(100),
OrderDate date,
OrderTime time,
OrderDateTime timestamp,
Status varchar(100),
TotalAmount numeric,
DeliveryTime_minutes numeric
);

-- Create Table Customers

Create table Customers
(CustomerID varchar(50) primary key,
Name varchar(100),
City varchar(100),
Area varchar(100),	
Email varchar(100),
Phone numeric,
JoinDate date,
TotalOrders numeric,
LastOrderDate date
);


-- Business Problem


-- Assignment Questions:
-- Part A: SQL Proficiency (Operational Analysis)

--1. Calculate the average delivery time for all orders in each city.

select * from Orders
select * from Customers
select C.city,AVG(O.Deliverytime_minutes) as Average_Delivery_Time
from Orders O
join Customers C
On O.customerid=C.customerid
Group by C.City;

--2. Find the top 3 customers based on the total order value they have placed.

select * from orders
select * from customers
select c.customerid,c,name,sum(c.totalorders) as Total_Orders_value
from orders o
join customers c
on o.customerid=c.customerid
where o.status='completed'
group by c.customerid,c.name
order by Total_Orders_Value desc
limit 3;


--3. Retrieve the top 3 most frequently ordered products in Mumbai.

select p.productid,p.productname,
sum(od.quantity) as Total_orders
from order_details od
join products p
on p.productid=od.productid
join orders o
on od.orderid=o.orderid
join stores s 
on s.storeid=o.storeid
where s.city='mumbai'
group by p.productid,p.productname
order by Total_orders desc
limit 3;

--4. Identify the number of customers who have not placed an order in the last 30 days.

select * from customers
select * from orders
select count(distinct customerid) as 
customer_not_ordered_in_last_30_days
from customers c
left join 
orders o
on c.customerid=o.customerid and o.status='completed'
and o.orderdate>=date_sub(curdate(),interval 30 day)
where o.orderid is null;

--5. Calculate the total revenue generated by each store.

select * from stores
select * from orders
select s.storeid,s.city,s.area,
coalesce(sum(o.totalamount),0) as Total_revenue
from stores s
left join orders o
on s.storeid=o.storeid
group by 
s.storeid,s.city,s.area;


-- Part B: Problem Solving (Customer Retention & Churn Analysis)

-- 1. Write a SQL query to identify customers who placed only one order in the last 3 months.

select * from customers
select * from orders
select c.customerid,c.name from customers c
where c.totalorders=1 and c.customerid IN (select o.customerid from orders o
where o.orderdate>=date_sub(curdate(),interval 3 month)
and o.status='completed');

-- 2. Create a list of cities with high percentages of single-order customers.

select * from customers
select c.city,count(c.customerid) as totalcustomers,
sum(case when c.totalorders=1 then 1 else 0 end) as single_order_customers,
(sum(case when c.totalorders=1 then 1 else 0 end)/
count(c.customerid))* 100 as percentage_single_order_customers
from customers c
group by c.city
order by percentage_single_order_customers desc;





